version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        patterns:
          - "github.com/hashicorp/terraform-*"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
